#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────
# Comply AI — First-run setup script
# Creates .env, verifies dependencies, runs migrations
# ──────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

echo ""
echo "  Comply AI — Setup"
echo "  ─────────────────────────────────────"
echo ""

# ── Check dependencies ──────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "  [!] $1 is not installed. Please install $1 first."
    exit 1
  fi
}

check_command docker
check_command node
echo "  [ok] Dependencies verified (docker, node)"

# ── Create .env if missing ──────────────────────────────

ENV_FILE="$ROOT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "  [ok] .env already exists — skipping"
else
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  cat >"$ENV_FILE" <<EOF
# Comply AI Environment Configuration
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Database
DATABASE_URL=postgres://comply:comply@localhost:5432/complyai

# Redis
REDIS_URL=redis://localhost:6379

# NextAuth
NEXTAUTH_URL=http://localhost:3300
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Server
PORT=3300
NODE_ENV=development
EOF
  echo "  [ok] .env created with generated NEXTAUTH_SECRET"
fi

# ── Install npm dependencies ────────────────────────────

if [ -d "$ROOT_DIR/node_modules" ]; then
  echo "  [ok] node_modules exists — skipping npm install"
else
  echo "  [..] Installing npm dependencies..."
  cd "$ROOT_DIR" && npm install
  echo "  [ok] npm dependencies installed"
fi

# ── Build core package ──────────────────────────────────

if [ -d "$ROOT_DIR/packages/core/dist" ]; then
  echo "  [ok] packages/core/dist exists — skipping build"
else
  echo "  [..] Building @comply-ai/core..."
  cd "$ROOT_DIR" && npm run build --workspace=packages/core 2>/dev/null || true
  echo "  [ok] Core package built"
fi

# ── Database migrations (placeholder) ───────────────────

echo "  [..] Database migrations: skipped (in-memory storage active)"
echo "       Run 'npm run db:push --workspace=packages/web' when Postgres is configured"

# ── Done ────────────────────────────────────────────────

echo ""
echo "  Setup complete! Next steps:"
echo ""
echo "    docker compose up -d          # Start all services"
echo "    npm run dev --workspace=packages/web  # Or run locally"
echo ""
echo "    Dashboard: http://localhost:3300"
echo ""
